### ISSUE TITLE
Understanding adjaceny matrix

### ISSUE THREAD

**Issue by guozixunnicolas** [davide-belli/toulouse-road-network-dataset#1]
Hi Davide,

Thank you very much for the work.

I have some trouble understanding the adjaceny matrix. For instance a graph with n nodes. The bfs adjaceny matrix will have dimension(n, max_prev_node). I wonder what does each "slice" (1, max_prev_node) represent? 

Thank you!

Best,

Nicolas

**Comment by davide-belli** [comment]
Hi Nicolas,

Happy to hear about your interest in our work!

Each "slice" (1, max_prev_node) describes whether that nodes is connected
(1) or not (0) with each of the previous "max_prev_node" nodes in the bfs
ordering. The adjancy matrix has binary values, meaning that the
connections or edges in the graph are unweighted.

You can find an example of bfs ordering in Fig.7 of our blogpost:
https://davide-belli.github.io/toulouse-road-network.
The attached image might also help you understanding the slicing. In the
image they talk about bfs frontier. In our case this is the same as the
last nodes in the bfs ordering.

Let me know if you have any other questions and good luck with your project.

Best,
Davide
